import type { NextPage } from 'next'
import Head from 'next/head'
import { BreakfastHeader } from '../components/BreakfastHeader'
import { EditMenuCard } from '../components/EditMenuCard'
import { SuggestFood } from '../components/SuggestFood'
import { AiOutlineExclamationCircle } from 'react-icons/ai'
import { BiTimeFive } from 'react-icons/bi'
import { RiMoneyCnyCircleLine } from 'react-icons/ri'
import { useState } from 'react'
import { Menu } from 'globalType'

const EditMenuPage: NextPage = () => {
  const [menuCards, setMenuCard] = useState <Menu[]>([]);
  let copyMenuCards = [...menuCards];

  const addMenuCard = () => {
    copyMenuCards.push({id:copyMenuCards.length+1});
    setMenuCard(copyMenuCards);
  }
  const removeMenuCard = (index: number) => {
    copyMenuCards.splice(index, 1)

    setMenuCard(copyMenuCards);
  }


  return (
    <div className="font-fancy">
      <Head>
        <title>Nutrition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@500&family=Yomogi&family=Zen+Maru+Gothic:wght@900&display=swap" rel="stylesheet"></link>
      </Head>
      <BreakfastHeader />
      {
      menuCards.map((menuCard :Menu,index :number)=>
        <EditMenuCard key={menuCard.id} index = {index} menu={menuCard} removeMenuCard={removeMenuCard}/>
      )
      }

      <div className="flex justify-center my-5">
        <button onClick={addMenuCard} className="active:scale-90 active:text-red-600 bg-orange-500 text-white text-center p-2 rounded-full w-1/2 shadow-lg">
          <div>+ 料理を追加する</div>
        </button>
      </div>

    </div>
  )
}
export default EditMenuPage;