import type { NextPage } from 'next'
import Head from 'next/head'
import { BreakfastHeader } from '../components/BreakfastHeader'
import { EditMenuCard }from '../components/editMenuCard'
import { SuggestFood } from '../components/SuggestFood'
import { AiOutlineExclamationCircle } from 'react-icons/ai'
import { BiTimeFive } from 'react-icons/bi'
import { RiMoneyCnyCircleLine } from 'react-icons/ri'
import { useState } from 'react'

const EditMenuPage: NextPage = () => {
  const [menuCard,setMenuCard] = useState([]);

  
  return (
    <div className="font-fancy">
      <Head>
        <title>Nutrition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@500&family=Yomogi&family=Zen+Maru+Gothic:wght@900&display=swap" rel="stylesheet"></link>
      </Head>
      <BreakfastHeader />
      <EditMenuCard />

  
    </div>
  )
}
export default EditMenuPage;