import type { NextPage } from "next";
import React, { useCallback, useContext, useEffect, useMemo } from "react";
import { DayContext } from "./_app";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Header } from "../components/common/Header";
import { DailylIntakeNutrition } from "../components/index/DailylIntakeNutrition";
import { DishCard } from "../components/index/DishCard";
import { SuggestFood } from "../components/editMenu/SuggestFood";
import { UserData, dayData, Meal } from "globalType";
import { useSelectDay } from "../hooks/useSelectDay";

const Home: NextPage = () => {
  const selectedDayData: dayData = useContext(DayContext);
  const meals = useMemo(() => {
    selectedDayData.meals = [
      { whenMeal: "breakfast" },
      { whenMeal: "lunch" },
      { whenMeal: "dinner" },
      { whenMeal: "snack" },
    ];
    return selectedDayData.meals;
  }, []);

  return (
    <div className="font-fancy">
      <Head>
        <title>Nutrition App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@500&family=Yomogi&family=Zen+Maru+Gothic:wght@900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header meal={""} isEdit={false} date={selectedDayData.selectedDay} />
      <DailylIntakeNutrition totalIntake={selectedDayData.totalIntake} />
      <div className="lg:flex flex-wrap">
        {meals.map((meal: Meal, index: number) => (
          <DishCard meal={meal} key={index} />
        ))}
      </div>
    </div>
  );
};

export default Home;
