import { RiNumber0 } from "react-icons/ri";
import { Menu } from "../shared/globalType";
export const dummyMenu: Menu[] = [
  {
    id: 0,
    totalNutrition: {
      calorie: 0,
      carbohydrates: 0,
      protein: 0,
      lipids: 0,
      suger: 0,
      dietaryFiber: 0,
      salt: 0,
      na: 0,
      k: 0,
      ca: 0,
      mg: 0,
      p: 0,
      fe: 0,
      zn: 0,
      cu: 0,
      mn: 0,
      i: 0,
      se: 0,
      cr: 0,
      mo: 0,
      vitA: 0,
      vitD: 0,
      vitE: 0,
      vitK: 0,
      vitB1: 0,
      vitB2: 0,
      vitB6: 0,
      vitB12: 0,
      vitC: 0,
      niacin: 0,
      pantothenicAcid: 0,
      folate: 0,
      biotin: 0,
    },
  },
];
